# Received Constants, used to identify the type of request: (Directory = Annuaire)
CONNEXION_TYPE = "CONNEXION" # Provided => {"username": "username", "password": "password"}
DISCONNECT_TYPE = "DISCONNECT" # Provided => {}

# Directory
LOOK_DIRECTORY = "LOOK_DIRECTORY"
ADD_CONTACT_TYPE = "ADD_CONTACT"
EDIT_CONTACT_TYPE = "EDIT_CONTACT"
REMOVE_CONTACT_TYPE = "REMOVE_CONTACT"
SEARCH_CONTACT_TYPE = "SEARCH_CONTACT"

# Share Directory
LIST_DIRECTORIES_TYPE = "LIST_DIRECTORIES"
LIST_USER_TO_DIRECTORY_TYPE = "LIST_USER_TO_DIRECTORY"
ADD_USER_TO_DIRECTORY_TYPE = "ADD_USER_TO_DIRECTORY"
REMOVE_USER_TO_DIRECTORY_TYPE = "REMOVE_USER_TO_DIRECTORY"

# Admin
LIST_USERS_TYPE = "LIST_USERS"
USER_INFO_TYPE = "USER_INFO"
ADD_USER_TYPE = "ADD_USER"
REMOVE_USER_TYPE = "REMOVE_USER"
EDIT_USER_TYPE = "EDIT_USER"

# Sent Constants, used to identify the type of request: (Directory = Annuaire)
CONNEXION_OK_TYPE = "CONNEXION_OK" # Provided => {"message": "Valid Credentials", "token": token}
DISCONNECT_OK_TYPE = "DISCONNECT_OK"
RESPONSE_OK_TYPE = "RESPONSE_OK"
ERROR_TYPE = "ERROR"